import unittest
from ..weakiddict import WeakIDDict as WeakIDDict, WeakIDKeyDict as WeakIDKeyDict
from typing import Any

class AllTheSame:
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

class WeakreffableInt:
    value: Any = ...
    def __init__(self, value: Any) -> None: ...
    def __hash__(self) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...

class TestWeakIDDict(unittest.TestCase):
    def test_weak_keys(self) -> None: ...
    def test_weak_keys_values(self) -> None: ...
