import unittest
from traits.util.event_tracer import CallingMessageRecord as CallingMessageRecord, ChangeMessageRecord as ChangeMessageRecord, ExitMessageRecord as ExitMessageRecord, SentinelRecord as SentinelRecord

class TestMessageRecords(unittest.TestCase):
    def test_base_message_record(self) -> None: ...
    def test_change_message_record(self) -> None: ...
    def test_exit_message_record(self) -> None: ...
    def test_calling_message_record(self) -> None: ...
