import unittest
from traits import trait_notifiers as trait_notifiers
from traits.api import Bool as Bool, Float as Float, HasTraits as HasTraits, List as List, on_trait_change as on_trait_change
from traits.util.event_tracer import ChangeEventRecorder as ChangeEventRecorder, MultiThreadChangeEventRecorder as MultiThreadChangeEventRecorder, MultiThreadRecordContainer as MultiThreadRecordContainer, RecordContainer as RecordContainer, record_events as record_events
from typing import Any

class TestObject(HasTraits):
    number: Any = ...
    list_of_numbers: Any = ...
    flag: Any = ...
    def add_to_number(self, value: Any) -> None: ...

class TestRecordEvents(unittest.TestCase):
    directory: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_change_event_recorder(self) -> None: ...
    def test_multi_thread_change_event_recorder(self) -> None: ...
    def test_record_events(self) -> None: ...
