import unittest
from traits.util.event_tracer import MultiThreadRecordContainer as MultiThreadRecordContainer, RecordContainer as RecordContainer, SentinelRecord as SentinelRecord
from typing import Any

class TestRecordContainers(unittest.TestCase):
    directory: Any = ...
    filename: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_record_container(self) -> None: ...
    def test_multi_thread_record_container(self) -> None: ...
