import unittest
from traits.testing.api import UnittestTools as UnittestTools
from traits.util.api import deprecated as deprecated
from typing import Any

def my_deprecated_addition(x: Any, y: Any): ...
def my_bad_function() -> None: ...

class ClassWithDeprecatedBits:
    def bits(self): ...
    def bytes(self, required_arg: Any, *args: Any, **kwargs: Any): ...

class TestDeprecated(unittest.TestCase, UnittestTools):
    def test_deprecated_function(self) -> None: ...
    def test_deprecated_exception_raising_function(self) -> None: ...
    def test_deprecated_method(self) -> None: ...
    def test_deprecated_method_with_fancy_signature(self) -> None: ...
