import unittest
from traits.util.api import import_symbol as import_symbol

class TestImportSymbol(unittest.TestCase):
    def test_import_dotted_symbol(self) -> None: ...
    def test_import_nested_symbol(self) -> None: ...
    def test_import_dotted_module(self) -> None: ...
