import unittest.mock
from traits.api import HasTraits as HasTraits, Int as Int
from traits.testing.optional_dependencies import requires_sphinx as requires_sphinx, sphinx as sphinx
from traits.util.trait_documenter import TraitDocumenter as TraitDocumenter
from typing import Any

class MyTestClass(HasTraits):
    bar: Any = ...

class TestTraitDocumenter(unittest.TestCase):
    source: str = ...
    tokens: Any = ...
    def setUp(self) -> None: ...
    def test_get_definition_tokens(self) -> None: ...
    def test_add_line(self) -> None: ...
    def test_abbreviated_annotations(self) -> None: ...
    def create_directive(self) -> None: ...
    def tmpdir(self) -> None: ...
