import unittest
from traits import trait_notifiers as trait_notifiers
from traits.api import Float as Float, HasTraits as HasTraits, List as List
from typing import Any

class ExtendedNotifiers(HasTraits):
    def __init__(self, **traits: Any) -> None: ...
    ok: Any = ...
    fail: Any = ...
    rebind_calls_0: Any = ...
    rebind_calls_1: Any = ...
    rebind_calls_2: Any = ...
    rebind_calls_3: Any = ...
    rebind_calls_4: Any = ...
    exceptions_from: Any = ...
    def method_listener_0(self) -> None: ...
    def method_listener_1(self, new: Any) -> None: ...
    def method_listener_2(self, name: Any, new: Any) -> None: ...
    def method_listener_3(self, obj: Any, name: Any, new: Any) -> None: ...
    def method_listener_4(self, obj: Any, name: Any, old: Any, new: Any) -> None: ...
    def failing_method_listener_0(self) -> None: ...
    def failing_method_listener_1(self, new: Any) -> None: ...
    def failing_method_listener_2(self, name: Any, new: Any) -> None: ...
    def failing_method_listener_3(self, obj: Any, name: Any, new: Any) -> None: ...
    def failing_method_listener_4(self, obj: Any, name: Any, old: Any, new: Any) -> None: ...

calls_0: Any

def function_listener_0() -> None: ...

calls_1: Any

def function_listener_1(new: Any) -> None: ...

calls_2: Any

def function_listener_2(name: Any, new: Any) -> None: ...

calls_3: Any

def function_listener_3(obj: Any, name: Any, new: Any) -> None: ...

calls_4: Any

def function_listener_4(obj: Any, name: Any, old: Any, new: Any) -> None: ...

exceptions_from: Any

def failing_function_listener_0() -> None: ...
def failing_function_listener_1(new: Any) -> None: ...
def failing_function_listener_2(name: Any, new: Any) -> None: ...
def failing_function_listener_3(obj: Any, name: Any, new: Any) -> None: ...
def failing_function_listener_4(obj: Any, name: Any, old: Any, new: Any) -> None: ...

class TestExtendedNotifiers(unittest.TestCase):
    exceptions: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_extended_notifiers_methods(self) -> None: ...
    def test_extended_notifiers_methods_failing(self) -> None: ...
    def test_extended_notifiers_functions(self) -> None: ...
    def test_extended_notifiers_functions_failing(self) -> None: ...
