import unittest
from traits.api import HasTraits as HasTraits, Instance as Instance, Int as Int

class TestCase(unittest.TestCase):
    count: int = ...
    def test_simple(self) -> None: ...
    def test_extended(self) -> None: ...
