import unittest
from traits.api import HasTraits as HasTraits, Subclass as Subclass, TraitError as TraitError, Type as Type

class BaseClass: ...
class DerivedClass(BaseClass): ...
class UnrelatedClass: ...
class ExampleTypeModel(HasTraits): ...
class ExampleSubclassModel(HasTraits): ...

class TypeTestCase(unittest.TestCase):
    def test_type_base(self) -> None: ...
    def test_type_derived(self) -> None: ...
    def test_invalid_type(self) -> None: ...
    def test_subclass_base(self) -> None: ...
    def test_subclass_derived(self) -> None: ...
    def test_invalid_subclass(self) -> None: ...
