import unittest
from traits.api import HasTraits as HasTraits, Int as Int, Str as Str, TraitError as TraitError
from typing import Any

class Foo(HasTraits):
    num: Any = ...
    bar: Any = ...

class Bar(HasTraits):
    PubT1: Any = ...
    PubT2: Any = ...
    PrivT1: Any = ...
    PrivT2: Any = ...

class FooBar(HasTraits):
    num: Any = ...
    baz: str = ...

class GetTraitTestCase(unittest.TestCase):
    def test_trait_set_bad(self) -> None: ...
    def test_trait_set_replaced(self) -> None: ...
    def test_trait_set_replaced_and_check(self) -> None: ...
    def test_trait_names_returned_by_visible_traits(self) -> None: ...
    def test_dir(self) -> None: ...
