import unittest
from traits.api import Float as Float, HasRequiredTraits as HasRequiredTraits, Int as Int, String as String, TraitError as TraitError
from typing import Any

class TestHasRequiredTraits(unittest.TestCase):
    def test_trait_value_assignment(self) -> None: ...
    def test_missing_required_trait(self) -> None: ...

class RequiredTest(HasRequiredTraits):
    i_trait: Any = ...
    f_trait: Any = ...
    s_trait: Any = ...
    non_req_trait: Any = ...
    normal_trait: Any = ...
