import unittest
from traits.api import Directory as Directory, HasTraits as HasTraits, TraitError as TraitError
from typing import Any

class ExampleModel(HasTraits):
    path: Any = ...

class FastExampleModel(HasTraits):
    path: Any = ...

class DirectoryTestCase(unittest.TestCase):
    def test_valid_directory(self) -> None: ...
    def test_invalid_directory(self) -> None: ...
    def test_file(self) -> None: ...
    def test_invalid_type(self) -> None: ...
    def test_fast(self) -> None: ...
