import unittest
from traits import trait_notifiers as trait_notifiers
from traits.api import Float as Float, HasTraits as HasTraits, Undefined as Undefined
from typing import Any

class AnytraitStaticNotifiers0Fail(HasTraits):
    fail: Any = ...

class AnytraitStaticNotifiers1Fail(HasTraits):
    fail: Any = ...

class AnytraitStaticNotifiers2Fail(HasTraits):
    fail: Any = ...

class AnytraitStaticNotifiers3Fail(HasTraits):
    fail: Any = ...

class AnytraitStaticNotifiers4Fail(HasTraits):
    fail: Any = ...

class TestNotifiers(unittest.TestCase):
    exceptions: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_anytrait_static_notifiers_0(self) -> None: ...
    anycalls: Any = ...
    def test_anytrait_static_notifiers_1(self) -> None: ...
    def test_anytrait_static_notifiers_2(self) -> None: ...
    def test_anytrait_static_notifiers_3(self) -> None: ...
    def test_anytrait_static_notifiers_4(self) -> None: ...
    def test_anytrait_static_notifiers_0_fail(self) -> None: ...
    def test_anytrait_static_notifiers_1_fail(self) -> None: ...
    def test_anytrait_static_notifiers_2_fail(self) -> None: ...
    def test_anytrait_static_notifiers_3_fail(self) -> None: ...
    def test_anytrait_static_notifiers_4_fail(self) -> None: ...
