import unittest
from traits.api import HasTraits as HasTraits, Int as Int, List as List, pop_exception_handler as pop_exception_handler, push_exception_handler as push_exception_handler
from traits.testing.unittest_tools import UnittestTools as UnittestTools
from typing import Any

class A(HasTraits):
    t: Any = ...
    l: Any = ...

class B(HasTraits):
    t: Any = ...
    u: Any = ...
    l: Any = ...

class TestSyncTraits(unittest.TestCase, UnittestTools):
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_mutual_sync(self) -> None: ...
    def test_sync_alias(self) -> None: ...
    def test_one_way_sync(self) -> None: ...
    def test_sync_lists(self) -> None: ...
    def test_sync_lists_partial_slice(self) -> None: ...
    def test_sync_delete(self) -> None: ...
    def test_sync_delete_one_way(self) -> None: ...
    def test_sync_ref_cycle(self) -> None: ...
