import logging
import unittest
from traits.api import HasTraits as HasTraits, Int as Int, Str as Str
from traits.testing.unittest_tools import UnittestTools as UnittestTools
from typing import Any

class TraitsObject(HasTraits):
    string: Any = ...
    integer: Any = ...

class ListHandler(logging.Handler):
    records: Any = ...
    def __init__(self) -> None: ...
    def emit(self, record: Any) -> None: ...

def catch_logs(module_name: Any) -> None: ...

class TestTraitGet(UnittestTools, unittest.TestCase):
    def test_trait_set(self) -> None: ...
    def test_trait_get(self) -> None: ...
    def test_trait_set_deprecated(self) -> None: ...
    def test_trait_get_deprecated(self) -> None: ...
