import unittest
from traits.adaptation.api import reset_global_adaptation_manager as reset_global_adaptation_manager
from traits.api import HasTraits as HasTraits, Instance as Instance, List as List, TraitError as TraitError, register_factory as register_factory
from typing import Any

class Foo(HasTraits): ...
class Bar(HasTraits): ...

def bar_to_foo_adapter(bar: Any): ...

class FooContainer(HasTraits):
    not_adapting_foo: Any = ...
    adapting_foo: Any = ...
    not_adapting_foo_list: Any = ...
    adapting_foo_list: Any = ...

class TestAutomaticAdaptation(unittest.TestCase):
    def setUp(self) -> None: ...
    def test_instance_trait_automatic_adaptation(self) -> None: ...
    def test_list_trait_automatic_adaptation(self) -> None: ...
