import unittest

class TestVersion(unittest.TestCase):
    def test_dunder_version(self) -> None: ...
    def test_version_version(self) -> None: ...
    def test_version_git_revision(self) -> None: ...
    def test_versions_match(self) -> None: ...
