import unittest
from traits.api import Any as Any, Bool as Bool, Delegate as Delegate, Event as Event, HasTraits as HasTraits, Instance as Instance, Property as Property, Str as Str

class Foo(HasTraits):
    a: Any = ...
    b: Any = ...
    s: Any = ...
    i: Any = ...
    e: Any = ...
    d: Any = ...
    p: Any = ...
    p_ro: Any = ...
    p_wo: Any = ...

class TestCopyableTraitNames(unittest.TestCase):
    names: Any = ...
    def setUp(self) -> None: ...
    def test_events_not_copyable(self) -> None: ...
    def test_read_only_property_not_copyable(self) -> None: ...
    def test_write_only_property_not_copyable(self) -> None: ...
    def test_any_copyable(self) -> None: ...
    def test_bool_copyable(self) -> None: ...
    def test_str_copyable(self) -> None: ...
    def test_instance_copyable(self) -> None: ...
    def test_delegate_copyable(self) -> None: ...
    def test_property_copyable(self) -> None: ...

class TestCopyableTraitNameQueries(unittest.TestCase):
    foo: Any = ...
    def setUp(self) -> None: ...
    def test_type_query(self): ...
    def test_property_query(self): ...
    def test_unmodified_query(self): ...
    def test_queries_not_combined(self): ...
