import unittest
from traits.editor_factories import BytesEditors as BytesEditors, MultilineTextEditors as MultilineTextEditors, PasswordEditors as PasswordEditors, bytes_editor as bytes_editor, list_editor as list_editor, multi_line_text_editor as multi_line_text_editor, password_editor as password_editor
from traits.has_traits import HasTraits as HasTraits
from traits.testing.optional_dependencies import requires_traitsui as requires_traitsui, traitsui as traitsui
from traits.trait_types import Instance as Instance, List as List, Str as Str
from typing import Any

DatetimeEditor: Any

class SimpleEditorTestMixin:
    factory: Any = ...
    traitsui_factory: Any = ...
    def setUp(self) -> None: ...
    def test_editor(self) -> None: ...

class SimpleEditorWithCachingTestMixin(SimpleEditorTestMixin):
    def tearDown(self) -> None: ...
    def test_editor_caching(self) -> None: ...

class TestDateEditor(SimpleEditorWithCachingTestMixin, unittest.TestCase):
    cache_name: str = ...
    traitsui_name: str = ...
    factory_name: str = ...

class TestDatetimeEditor(SimpleEditorTestMixin, unittest.TestCase):
    traitsui_name: str = ...
    factory_name: str = ...

class TestCodeEditor(SimpleEditorWithCachingTestMixin, unittest.TestCase):
    cache_name: str = ...
    traitsui_name: str = ...
    factory_name: str = ...

class TestHTMLEditor(SimpleEditorWithCachingTestMixin, unittest.TestCase):
    cache_name: str = ...
    traitsui_name: str = ...
    factory_name: str = ...

class TestShellEditor(SimpleEditorWithCachingTestMixin, unittest.TestCase):
    cache_name: str = ...
    traitsui_name: str = ...
    factory_name: str = ...

class TestTimeEditor(SimpleEditorWithCachingTestMixin, unittest.TestCase):
    cache_name: str = ...
    traitsui_name: str = ...
    factory_name: str = ...

class TestBytesEditor(unittest.TestCase):
    def tearDown(self) -> None: ...
    def test_bytes_editor_default(self) -> None: ...
    def test_bytes_editor_options(self) -> None: ...
    def test_bytes_editor_caching(self) -> None: ...

class TestMultiLineEditor(unittest.TestCase):
    def tearDown(self) -> None: ...
    def test_multi_line_text_editor_default(self) -> None: ...
    def test_multi_line_text_editor_options(self) -> None: ...
    def test_multi_line_text_editor_caching(self) -> None: ...

class TestPasswordEditor(unittest.TestCase):
    def tearDown(self) -> None: ...
    def test_password_editor_default(self) -> None: ...
    def test_password_editor_options(self) -> None: ...
    def test_password_editor_caching(self) -> None: ...

class TestListEditor(unittest.TestCase):
    def test_list_editor_default(self) -> None: ...
    def test_list_editor_options(self) -> None: ...
    def test_list_editor_list_instance(self) -> None: ...
