import unittest
from traits.api import HasTraits as HasTraits, Int as Int
from typing import Any

class A(HasTraits):
    x: Any = ...

class TestGetAttr(unittest.TestCase):
    a: Any = ...
    def setUp(self) -> None: ...
    def test_bad__getattribute__(self) -> None: ...
