import unittest.mock
from traits.api import HasTraits as HasTraits, Int as Int
from traits.testing.optional_dependencies import requires_traitsui as requires_traitsui, traitsui as traitsui
from typing import Any

class Model(HasTraits):
    count: Any = ...

class TestConfigureTraits(unittest.TestCase):
    toolkit: Any = ...
    tmpdir: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_simple_call(self) -> None: ...
    def test_filename_but_no_file(self) -> None: ...
    def test_pickle_protocol(self) -> None: ...
    def test_filename_with_existing_file(self) -> None: ...
    def test_filename_with_invalid_existing_file(self) -> None: ...
    def test_filename_with_existing_file_stores_updated_model(self): ...
