import unittest
from traits.api import HasTraits as HasTraits, Int as Int, Range as Range, TraitError as TraitError
from typing import Any

class A(HasTraits):
    i: Any = ...
    r: Any = ...

class TraitIntRange(unittest.TestCase):
    def test_int(self) -> None: ...
    def test_range(self) -> None: ...
