import unittest
from traits.api import HasStrictTraits as HasStrictTraits, Int as Int, TraitError as TraitError
from traits.tests.tuple_test_mixin import TupleTestMixin as TupleTestMixin
from traits.trait_types import ValidatedTuple as ValidatedTuple
from typing import Any

class Simple(HasStrictTraits):
    scalar_range: Any = ...

class ValidatedTupleTestCase(TupleTestMixin, unittest.TestCase):
    trait: Any = ...
    def setUp(self) -> None: ...
    def test_initialization(self) -> None: ...
    def test_custom_validation(self) -> None: ...
    def test_error_during_custom_validation(self): ...
