import unittest
from traits import trait_notifiers as trait_notifiers
from traits.api import Float as Float, HasTraits as HasTraits, on_trait_change as on_trait_change
from typing import Any

class FuzException(Exception): ...

class Foo(HasTraits):
    bar: Any = ...
    baz: Any = ...
    fuz: Any = ...

class TestChangeEventTracers(unittest.TestCase):
    pre_change_events: Any = ...
    post_change_events: Any = ...
    exceptions: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_change_event_hooks(self) -> None: ...
    def test_change_event_hooks_after_exception(self) -> None: ...
