import unittest
from traits.api import HasTraits as HasTraits, TraitError as TraitError, UUID as UUID
from typing import Any

class A(HasTraits):
    id: Any = ...

class B(HasTraits):
    id: Any = ...

class TestUUID(unittest.TestCase):
    def test_bad_assignment(self) -> None: ...
    def test_bad_init(self) -> None: ...
    def test_good_init(self) -> None: ...
