import unittest
from traits.api import HasTraits as HasTraits, Trait as Trait, TraitError as TraitError, TraitHandler as TraitHandler
from traits.trait_base import strx as strx
from typing import Any

def validator(object: Any, name: Any, value: Any): ...

class MyHandler(TraitHandler):
    def validate(self, object: Any, name: Any, value: Any): ...
    def info(self): ...

class Foo(HasTraits):
    s: Any = ...

class Bar(HasTraits):
    s: Any = ...

class StrHandlerCase(unittest.TestCase):
    def test_validator_function(self) -> None: ...
    def test_validator_handler(self) -> None: ...
