import unittest
from traits.api import Any as Any, Int as Int
from traits.ctrait import CTrait as CTrait
from traits.trait_converters import as_ctrait as as_ctrait, check_trait as check_trait, trait_cast as trait_cast, trait_for as trait_for, trait_from as trait_from
from traits.trait_factory import TraitFactory as TraitFactory
from traits.trait_handlers import TraitCastType as TraitCastType, TraitInstance as TraitInstance

def reset_trait_factory() -> None: ...

class TestTraitCast(unittest.TestCase):
    def test_trait_cast_ctrait(self) -> None: ...
    def test_trait_cast_trait_type_class(self) -> None: ...
    def test_trait_cast_trait_type_instance(self) -> None: ...
    def test_trait_cast_trait_factory(self): ...
    def test_trait_cast_none(self) -> None: ...
    def test_trait_cast_other(self) -> None: ...

class TestTraitFrom(unittest.TestCase):
    def test_trait_from_ctrait(self) -> None: ...
    def test_trait_from_trait_type_class(self) -> None: ...
    def test_trait_from_trait_type_instance(self) -> None: ...
    def test_trait_from_trait_factory(self): ...
    def test_trait_from_none(self) -> None: ...
    def test_trait_from_other(self) -> None: ...

class TestCheckTrait(unittest.TestCase):
    def test_check_trait_ctrait(self) -> None: ...
    def test_check_trait_trait_type_class(self) -> None: ...
    def test_check_trait_trait_type_instance(self) -> None: ...
    def test_check_trait_trait_factory(self): ...
    def test_check_trait_none(self) -> None: ...
    def test_check_trait_other(self) -> None: ...

class TestTraitFor(unittest.TestCase):
    def test_trait_for_ctrait(self) -> None: ...
    def test_trait_for_trait_type_class(self) -> None: ...
    def test_trait_for_trait_type_instance(self) -> None: ...
    def test_trait_for_trait_factory(self): ...
    def test_trait_for_none(self) -> None: ...
    def test_trait_for_other(self) -> None: ...

class TestAsCtrait(unittest.TestCase):
    def test_as_ctrait_from_ctrait(self) -> None: ...
    def test_as_ctrait_from_class(self) -> None: ...
    def test_as_ctrait_from_instance(self) -> None: ...
    def test_as_ctrait_from_trait_factory(self): ...
    def test_as_ctrait_raise_exception(self) -> None: ...
