import unittest
from traits.api import HasTraits as HasTraits, Int as Int, List as List, Str as Str
from typing import Any

class A(HasTraits):
    x: Any = ...
    name: Any = ...

class B(A): ...

class C(B):
    lst: Any = ...
    y: Any = ...

class TestClassTraits(unittest.TestCase):
    def test_all_class_traits(self) -> None: ...
    def test_class_traits_with_metadata(self): ...
