import unittest
from traits.has_traits import HasTraits as HasTraits, on_trait_change as on_trait_change
from traits.trait_errors import TraitError as TraitError
from traits.trait_types import Dict as Dict, Event as Event, Str as Str, TraitDictObject as TraitDictObject
from typing import Any

def create_listener(): ...
def initialize_listener(listener: Any): ...

class TestDict(unittest.TestCase):
    modified: bool = ...
    def test_modified_event(self) -> None: ...
    def test_validate(self) -> None: ...
