import unittest
from traits.api import Any as Any, HasTraits as HasTraits, Int as Int, Property as Property, TraitError as TraitError

class E(HasTraits):
    a: Any = ...
    b: Any = ...

class TestPropertyDelete(unittest.TestCase):
    def test_property_delete(self) -> None: ...
    def test_property_reset_traits(self) -> None: ...
