import unittest
from traits.api import Any as Any, HasTraits as HasTraits, Property as Property

class Test(HasTraits):
    output_buffer: Any = ...
    value: Any = ...

class Test_1(Test): ...

class TestPropertyNotifications(unittest.TestCase):
    def test_property_notifications(self) -> None: ...
