import unittest
from traits.api import HasTraits as HasTraits, Instance as Instance, Int as Int
from typing import Any

class Bar(HasTraits):
    b: Any = ...

class Foo(HasTraits):
    bar: Any = ...

class KeyWordArgsTest(unittest.TestCase):
    def test_using_kw(self) -> None: ...
    def test_not_using_kw(self) -> None: ...
