import unittest
from traits.api import HasTraits as HasTraits, Int as Int, TraitError as TraitError
from traits.testing.optional_dependencies import requires_traitsui as requires_traitsui
from typing import Any

class TestViewElements(unittest.TestCase):
    toolkit: Any = ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def test_view_definition(self) -> None: ...
    def test_view_definition_twice(self) -> None: ...
    def test_view_elements_parents(self) -> None: ...
    def test_instance_view_definition(self) -> None: ...
    def test_trait_views(self) -> None: ...
    def test_included_names(self) -> None: ...
    def test_duplicate_names(self) -> None: ...
