import unittest
from traits.testing.optional_dependencies import cython as cython, requires_cython as requires_cython
from traits.testing.unittest_tools import UnittestTools as UnittestTools
from typing import Any

class CythonizedTraitsTestCase(unittest.TestCase, UnittestTools):
    def test_simple_default_methods(self) -> None: ...
    def test_basic_events(self) -> None: ...
    def test_on_trait_static_handlers(self) -> None: ...
    def test_on_trait_on_trait_change_decorator(self) -> None: ...
    def test_on_trait_properties(self) -> None: ...
    def test_on_trait_properties_with_standard_getter(self) -> None: ...
    def test_on_trait_aliasing(self) -> None: ...
    def test_on_trait_aliasing_different_scope(self) -> None: ...
    def execute(self, code: Any): ...
