import unittest
from traits.has_traits import HasTraits as HasTraits
from traits.testing.unittest_tools import UnittestTools as UnittestTools
from traits.trait_types import Str as Str, WeakRef as WeakRef
from typing import Any

class Eggs(HasTraits):
    name: Any = ...

class Spam(HasTraits):
    eggs: Any = ...

def restore_gc_state() -> None: ...

class TestWeakRef(UnittestTools, unittest.TestCase):
    def test_set_and_get(self) -> None: ...
    def test_target_freed_notification(self) -> None: ...
    def test_weakref_trait_doesnt_leak_cycles(self) -> None: ...
