import unittest
from traits.api import HasTraits as HasTraits, Instance as Instance, Str as Str
from typing import Any

class Shared(HasTraits):
    s: Any = ...

class Foo(HasTraits):
    s: Any = ...
    shared: Any = ...

class Bar(HasTraits):
    s: Any = ...
    foo: Any = ...
    shared: Any = ...

class Baz(HasTraits):
    s: Any = ...
    bar: Any = ...
    shared: Any = ...

class CopyTraitsBase(unittest.TestCase):
    __test__: bool = ...
    shared: Any = ...
    foo: Any = ...
    bar: Any = ...
    baz: Any = ...
    shared2: Any = ...
    foo2: Any = ...
    bar2: Any = ...
    baz2: Any = ...
    def setUp(self) -> None: ...
    def set_shared_copy(self, value: Any) -> None: ...

class TestCopyTraitsSetup(CopyTraitsBase):
    __test__: bool = ...
    def setUp(self) -> None: ...
    def test_setup(self) -> None: ...

class CopyTraits:
    def test_baz2_s(self) -> None: ...
    def test_baz2_bar_s(self) -> None: ...
    def test_baz2_bar_foo_s(self) -> None: ...
    def test_baz2_shared_s(self) -> None: ...
    def test_baz2_bar(self) -> None: ...
    def test_baz2_bar_foo(self) -> None: ...

class CopyTraitsSharedCopyNone:
    def test_baz2_shared(self) -> None: ...
    def test_baz2_bar_shared(self) -> None: ...
    def test_baz2_bar_foo_shared(self) -> None: ...
    def test_baz2_bar_and_foo_shared(self) -> None: ...

class TestCopyTraitsSharedCopyNone(CopyTraits, CopyTraitsSharedCopyNone):
    __test__: bool = ...
    def setUp(self) -> None: ...

class TestCopyTraitsCopyNotSpecified(CopyTraitsBase, TestCopyTraitsSharedCopyNone):
    __test__: bool = ...
    def setUp(self) -> None: ...

class TestCopyTraitsCopyShallow(CopyTraitsBase, TestCopyTraitsSharedCopyNone):
    __test__: bool = ...
    def setUp(self) -> None: ...

class TestCopyTraitsCopyDeep(CopyTraitsBase, TestCopyTraitsSharedCopyNone):
    __test__: bool = ...
    def setUp(self) -> None: ...

class CopyTraitsSharedCopyRef:
    def test_baz2_shared(self) -> None: ...
    def test_baz2_bar_shared(self) -> None: ...
    def test_baz2_bar_foo_shared(self) -> None: ...
    def test_baz2_bar_and_foo_shared(self) -> None: ...

class TestCopyTraitsSharedCopyRef(CopyTraits, CopyTraitsSharedCopyRef):
    __test__: bool = ...
    def setUp(self) -> None: ...

class TestCopyTraitsCopyNotSpecifiedSharedRef(CopyTraitsBase, TestCopyTraitsSharedCopyRef):
    __test__: bool = ...
    def setUp(self) -> None: ...

class TestCopyTraitsCopyShallowSharedRef(CopyTraitsBase, TestCopyTraitsSharedCopyRef):
    __test__: bool = ...
    def setUp(self) -> None: ...

class TestCopyTraitsCopyDeepSharedRef(CopyTraitsBase, TestCopyTraitsSharedCopyRef):
    __test__: bool = ...
    def setUp(self) -> None: ...
