import unittest
from traits.api import Any as Any, HasStrictTraits as HasStrictTraits, Str as Str

class TestSpecialEvent(unittest.TestCase):
    change_events: Any = ...
    foo: Any = ...
    def setUp(self) -> None: ...
    def test_events(self) -> None: ...
    def test_instance_events(self) -> None: ...

class Foo(HasStrictTraits):
    val: Any = ...
    test: Any = ...
