import unittest
from traits.api import Float as Float, HasTraits as HasTraits, ReadOnly as ReadOnly, Str as Str, Undefined as Undefined
from typing import Any

class Foo(HasTraits):
    name: Any = ...
    original_name: Any = ...
    bar: Any = ...
    baz: Any = ...

class Bar(HasTraits):
    name: Any = ...

class UndefinedTestCase(unittest.TestCase):
    def test_initial_value(self) -> None: ...
    def test_name_change(self) -> None: ...
    def test_read_only_write_once(self) -> None: ...
    def test_read_only_write_once_from_constructor(self) -> None: ...
