from traits.api import HasTraits as HasTraits, TraitError as TraitError
from traits.testing.unittest_tools import UnittestTools as UnittestTools
from typing import Any

VALUES: Any

class TupleTestMixin(UnittestTools):
    def test_default_values(self) -> None: ...
    def test_simple_assignment(self) -> None: ...
    def test_invalid_assignment_length(self) -> None: ...
    def test_type_checking(self) -> None: ...
