from typing import Any

class CamelCaseToPython:
    patn: Any = ...
    nd_patn: Any = ...
    def __init__(self) -> None: ...
    def __call__(self, name: Any): ...

camel_case_to_python: Any

def camel_case_to_words(s: Any): ...
