from typing import Any, Optional

def clean_filename(name: Any, replace_empty: str = ...): ...
def clean_timestamp(dt: Optional[Any] = ..., microseconds: bool = ...): ...
def python_name(name: Any): ...
