from typing import Any, Optional

def get_path(path: Any): ...
def create_unique_name(prefix: Any, names: Any, separator: str = ...): ...
def find_resource(project: Any, resource_path: Any, alt_path: Optional[Any] = ..., return_path: bool = ...): ...
def store_resource(project: Any, resource_path: Any, filename: Any) -> None: ...
