from collections.abc import MutableMapping
from typing import Any, Optional

class WeakIDDict(MutableMapping):
    data: Any = ...
    def __init__(self, dict: Optional[Any] = ...) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __len__(self): ...
    def __contains__(self, key: Any): ...
    def __iter__(self) -> Any: ...

class WeakIDKeyDict(WeakIDDict):
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
