from traits.api import Any as Any, Bool as Bool, HasTraits as HasTraits, Property as Property
from traits.util.api import import_symbol as import_symbol

class AdaptationOffer(HasTraits):
    factory: Any = ...
    from_protocol: Any = ...
    from_protocol_name: Any = ...
    to_protocol: Any = ...
    to_protocol_name: Any = ...
