from traits.has_traits import HasTraits as HasTraits
from traits.trait_types import Any as Any

class PurePythonAdapter:
    adaptee: Any = ...
    def __init__(self, adaptee: Any) -> None: ...

class Adapter(HasTraits):
    def __init__(self, adaptee: Any, **traits: Any) -> None: ...
    adaptee: Any = ...
