from .constants import DefaultValue as DefaultValue
from .trait_errors import TraitError as TraitError
from typing import Any, Optional

class BaseTraitHandler:
    default_value_type: Any = ...
    has_items: bool = ...
    is_mapped: bool = ...
    editor: Any = ...
    info_text: str = ...
    def is_valid(self, object: Any, name: Any, value: Any): ...
    def error(self, object: Any, name: Any, value: Any) -> None: ...
    def full_info(self, object: Any, name: Any, value: Any): ...
    def info(self): ...
    def get_editor(self, trait: Optional[Any] = ...): ...
    def create_editor(self): ...
    def inner_traits(self): ...
