from .constants import DefaultValue as DefaultValue
from .trait_errors import TraitError as TraitError
from typing import Any, Optional


class BaseTraitHandler:
    default_value_type: int = ...
    has_items: bool = ...
    is_mapped: bool = ...
    editor: Any = ...
    info_text: str = ...
    def is_valid(self, object: Any, name: str, value: Any) -> bool: ...
    def error(self, object: Any, name: str, value: Any) -> None: ...
    def full_info(self, object: Any, name: str, value: Any) -> str: ...
    def info(self) -> str: ...
    def get_editor(self, trait: Optional[Any] = ...) -> Any: ...
    def create_editor(self) -> Any: ...
    def inner_traits(self) -> tuple: ...
