from .trait_errors import TraitError as TraitError
from typing import Any, Optional

class TraitFactory:
    maker_function: Any = ...
    __doc__: Any = ...
    def __init__(self, maker_function: Optional[Any] = ...) -> None: ...
    def __call__(self, *args: Any, **metadata: Any): ...
    def as_ctrait(self): ...

class TraitImportError(TraitFactory):
    message: Any = ...
    def __init__(self, message: Any) -> None: ...
    def __call__(self, *args: Any, **metadata: Any) -> None: ...

def trait_factory(trait: Any): ...
