from typing import Any

def trait_cast(obj: Any): ...
def as_ctrait(obj: Any): ...
def check_trait(trait: Any): ...
try_trait_cast = check_trait

def trait_from(obj: Any): ...
def trait_for(trait: Any): ...
def mapped_trait_for(trait: Any): ...
