import unittest
from traits.adaptation.api import Adapter as Adapter
from traits.api import on_trait_change as on_trait_change

class TestAdapter(unittest.TestCase):
    post_init_notifier_called: bool = ...
    adaptee_notifier_called: bool = ...
    def test_initializing_adaptee(self) -> None: ...
