import unittest
from traits.adaptation.api import AdaptationError as AdaptationError, AdaptationManager as AdaptationManager, AdaptationOffer as AdaptationOffer, adapt as adapt, get_global_adaptation_manager as get_global_adaptation_manager, provides_protocol as provides_protocol, register_factory as register_factory, register_offer as register_offer, register_provides as register_provides, reset_global_adaptation_manager as reset_global_adaptation_manager, set_global_adaptation_manager as set_global_adaptation_manager, supports_protocol as supports_protocol
from typing import Any

class TestGlobalAdaptationManager(unittest.TestCase):
    examples: Any = ...
    def setUp(self) -> None: ...
    def test_reset_adaptation_manager(self) -> None: ...
    def test_set_adaptation_manager(self) -> None: ...
    def test_global_convenience_functions(self) -> None: ...
    def test_global_register_provides(self) -> None: ...
    def test_global_register_offer(self) -> None: ...
